version: "3.8"

services:

  # --- API Gateway (Ocelot + Swagger) ---
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    depends_on:
      - authservice
      - flightservice
      - bookingservice
    environment:
      JwtSettings__Key:      "1jG8rD9wXc0Qe4ZlP2b7Nf3sUv6HpR"
      JwtSettings__Issuer:   "SkyBookerAuthService"
      JwtSettings__Audience: "SkyBookerClient"
      ASPNETCORE_URLS:       "http://+:5000"
    ports:
      - "5000:5000"
    networks:
      - skybooker-net

  # --- MongoDB für FlightService ---
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # --- SQL Server für BookingService ---
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- FlightService ---
  flightservice:
    build:
      context: ./FlightService
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      FlightDatabaseSettings__ConnectionString:      "mongodb://mongo:27017"
      FlightDatabaseSettings__DatabaseName:          "SkyBookerDb"
      FlightDatabaseSettings__FlightsCollectionName: "flights"
      JwtSettings__Key:      "1jG8rD9wXc0Qe4ZlP2b7Nf3sUv6HpR"
      JwtSettings__Issuer:   "SkyBookerAuthService"
      JwtSettings__Audience: "SkyBookerClient"
      ASPNETCORE_URLS:       "http://+:8080"
    ports:
      - "8080:8080"
    networks:
      - skybooker-net

  # --- BookingService ---
  bookingservice:
    build:
      context: ./BookingService
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=BookingDb;User Id=sa;Password=YourStrong!Passw0rd;"
      ASPNETCORE_URLS:                     "http://+:8090"
    ports:
      - "8090:8090"
    networks:
      - skybooker-net

  # --- AuthService ---
  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    volumes:
      - auth-data:/data
    environment:
      ConnectionStrings__DefaultConnection:   "Data Source=/data/auth.db"
      JwtSettings__Key:      "1jG8rD9wXc0Qe4ZlP2b7Nf3sUv6HpR"
      JwtSettings__Issuer:   "SkyBookerAuthService"
      JwtSettings__Audience: "SkyBookerClient"
      JwtSettings__ExpiresInMinutes: "60"
      ASPNETCORE_URLS:       "http://+:8070"
    ports:
      - "8070:8070"
    networks:
      - skybooker-net

  # --- MessageService ---
  messageservice:
    build:
      context: ./MessageService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8100:80"
    environment:
      RabbitMq__Host:       "rabbitmq"
      RabbitMq__Username:   "guest"
      RabbitMq__Password:   "guest"
      RabbitMq__Queue:      "booking.created"
      Twilio__FromWhatsApp: "whatsapp:+14155238886"
      ASPNETCORE_URLS:      "http://+:8100"
    networks:
      - skybooker-net

  # --- RabbitMQ (Broker) ---
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - skybooker-net

networks:
  skybooker-net:

volumes:
  mongo-data:
  sqlserver-data:
  auth-data:
